# Generated by Django 5.2.1 on 2025-05-13 08:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('base_user', '0001_initial'),
        ('multimedia_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_image',
            field=models.ForeignKey(blank=True, help_text='Imagen de perfil del usuario', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile_image', to='multimedia_manager.mediafile', verbose_name='Imagen de perfil'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='foto',
            field=models.ForeignKey(blank=True, help_text='Foto del usuario', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_profile_foto', to='multimedia_manager.mediafile', verbose_name='Foto'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(help_text='Usuario del perfil', on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='usuario_pdf',
            field=models.ForeignKey(blank=True, help_text='Usuario PDF del usuario', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuario_pdf', to='multimedia_manager.documentfile', verbose_name='Usuario PDF'),
        ),
    ]
